### PR TITLE
Add SpaceportRemapTitle and fix SpaceportRemapDescription/ SpaceportRemapKey

### PR DESCRIPTION
**Pull request by HandyGold75**
Add support for SpaceportRemapTitle and fix up SpaceportRemapDescription/ SpaceportRemapKey for the remaps screen.

### CODE REVIEW

**Comment by CWood-sdf** [comment]
Thanks for the PR!

I just added a change that allows titles to be SpaceportWord's instead of plain strings (something I should have done a while ago, I was just too lazy to do it until necessary). Most of the other changes look really good especially the new name screen you put up. If there's any other changes you would like to make, let me know, otherwise I will merge this tomorrow.

**Comment by HandyGold75** [comment]
Thanks for the feedback,
The name screen was an accident (quite new to gh pr features), I wanted to push this separately as I wasn't sure if it would be in you're taste. I am happy to hear you do like it.

Currently, I'm looking to implement support for custom icons in titles like those shown below.
However this is going to take me a bit more time to implement properly (without making a dependency on devicons or nerdfont) as I'm still getting familiar with the project and Lua itself so don't wait on it.

image

**Comment by CWood-sdf** [comment]
yeah there's not really support for doing icons or anything like that right now, so i might have to make a few additions to some areas to improve that but i havent really figured that out yet. so if you could wait a few days before trying to implement that, that would be great!

**Comment by HandyGold75** [comment]
I would like to give my proposal for a solution, feel free to shoot it down if you already have something else implemented or if you simply don't like it.

My idea is to add opts for something like titles and icons, something like this (init.lua)
```Lua
local opts = {
-- ...
    titles = {
        Remaps = "Remaps",
        HackerNews = "Hacker News",
        Pinned = "Pinned",
        Today = "Today",
        Yesterday = "Yesterday",
        Week = "Past Week",
        Month = "Past Month",
        Long = "A long time ago",
    },
    icons = {
        File = "",
        Dir = ""
    },
-- ...
}
```

And using a get function like sections is doing (init.lua):
```Lua
---@return string
---@param title string
function M._getTitle(title)
    -- M.log(opts.titles[title])
    if opts.titles[title] then return opts.titles[title] else return title end
end

---@return string
---@param icon string
function M._getIcon(icon)
    -- M.log(opts.icons[icon])
    if opts.icons[icon] then return opts.icons[icon] else return icon end
end
```

After this screens like recent or remaps can call these functions to get the values associated with the opts, as an example of how this can be used in recent for pinned:
```Lua
-- ...
    if #pinned > 0 then
        lines = {
            "",
            { { require("spaceport")._getTitle("Pinned"), colorOpts = { _name = "SpaceportRecentsTitle" } } },
        }
        for _, v in ipairs(pinned) do
            linesToDir[#lines + 1] = i
            local prefix = require("spaceport")._getIcon("File")
            if v.isDir then prefix = require("spaceport")._getIcon("Dir") end
            ---@type SpaceportWord[]
            local words = {
                { prefix .. " " .. v.prettyDir, colorOpts = { _name = "SpaceportRecentsProject" } },
                { i .. "",     colorOpts = { _name = "SpaceportRecentsCount" } },
            }
            table.insert(lines, require("spaceport.screen").setWidthWords(words, largestLen))
            i = i + 1
        end
    end
-- ...
```

By doing it like this there should not be any breaking changes while still giving the user the options for icons and custom naming. By not including icons with the defaults there is no need to depend on specific icon packs.

As an example of how the user config could looks like:
```Lua
require("spaceport").setup({
	sections = { "_global_remaps", "name_blue", "remaps", "recents" },
	titles = {
		Remaps = " Remaps",
		Pinned = " Pinned",
		Today = " Today",
		Yesterday = " Yesterday",
		Week = " Week",
		Month = " Month",
		Long = " Longer",
	},
	icons = {
		File = "",
		Dir = "",
	},
})
```

image

**Comment by CWood-sdf** [comment]
I really like your idea to have file and directory icons. I think we could provide some default nerdfonts that can just be set via something like `icons = true` and icons can be disabled via `icons = false`. Then they could specialize them with `icons = { ... }` like you have right now. 

I am not as much a fan of your way of changing the titles. It feels a little to non-generalized for me which makes me feel like it would become a pain point in the future. Preferably, I could provide a way of overriding the configuration of a section. Probably something like:

```Lua
sections = {
  {
    "remaps",
    title = " Remaps",
  },
  "name_blue"
}
```

This would also allow users to change remaps and descriptions and custom configurations for each section. 

One thing I would *really* like to do is split up the `recents` section into multiple sections (eg `pinned`, `today`...). The only reason it's not like that right now is because when I tried to do it a while back, it was really ugly. 

Anyway, I would like to know your thoughts on these ideas, and I might push a few changes along theses lines.

**Comment by CWood-sdf** [comment]
I also am thinking about allowing each section to have a custom config property. This would make it so that all name ascii art versions and gradients can be combined into one screen (name), like:

```Lua
sections = {
  { 
    "name",
    config = {
      style = "hash",
      gradient = "blue_green" -- or
      gradient = {
       { start = "#0000ff", end = "#eeeeff", direction = "up" },
       { start = "#ff0000, end = "#ffeeee", direction = "left" },
      } -- would add those two gradients together, like in name_blue_green
  }
}
```

This would also allow custom filtering functions or other stuff to be added at a later time. 

Anyway, I kinda like the idea to have section configs, though it would be a little annoying documenting everything. I think it would be the best way to allow easy implementation of a lot of things you are looking for. 

Also, if you could add the implementation for file icons to this pr, that would be amazing. Preferably, the user should be able to say either `icons = true` (default icons), `icons = false` (no icons), or `icons = { file = "...", dir = "..." }` or something. I like the idea to have a `_getIcon()` function that is called in other places, so if you could add that implementation, that would be amazing!

**Comment by CWood-sdf** [comment]
> I think we could provide some default nerdfonts that can just be set via something like `icons = true` and icons can be disabled via `icons = false`. Then they could specialize them with `icons = { ... }` like you have right now.

I think if we also have `icons` set to a non-false value we can override the titles of sections to include icons

**Comment by HandyGold75** [comment]
Using a config property would definitely be better, this is way less clunky than my title idea and allows for easier expansion in the future. I'm still quite new to plugin design principles so thanks for bearing with me.
I also like the idea of merging the name screens, as this will also prevent clutter in case more logos are added.

Regarding the documentation of the config property, I'll think a short description under the `Customization` header will do (with the example above it updated `accordingly`), for eq:

> - `name`: This section displays an ascii art "Spaceport" logo
>   - `style`: Set a predefined style, choices: `hash`
>   - `gradient`:  Set a predefined gradiant, choices: `white`, `blue`, `blue_blue`

Regarding splitting up the recent section, I see what you're getting at but don't think that's a good idea as it does increase complexity quite a lot. There is a clear option for the user (`lastViewTime`) to cut off unwanted parts unless the user doesn't want the last week but does want the last month. This would also need consideration of which the `month` section should include the last week as the `week` section should cover this but might not be picked by the user.

Maybe an option for selectively enabling/ disabling the titles in some way would do the trick if a single big list is desired, maybe like this although it isn't very pretty:
```Lua
sections = {
  { 
    "recent",
    config = {
      titles = {
       today = true,
       week = false,
       month = true,
       long = false
      }
  }
}
```

At last, I'll get the commit for the icons ready, It will come when it's ready.

**Comment by HandyGold75** [comment]
> > I think we could provide some default nerdfonts that can just be set via something like `icons = true` and icons can be disabled via `icons = false`. Then they could specialize them with `icons = { ... }` like you have right now.
> 
> I think if we also have `icons` set to a non-false value we can override the titles of sections to include icons

If I'm getting this right do you mean in a sense that icons can be configured like:

```Lua
require("spaceport").setup({
	icons = {
		File = "",
		Dir = "",
		Remaps = "",
		Pinned = "",
		Today = "",
		Yesterday = "",
		Week = "",
		Month = "",
		Long = "",
	},
})
```

And that the `_getIcon()` function can be used to prefix the titles?
Or do you mean that instead of prefixing the icon value can be used to completely replace the title?
I'm guessing you mean prefix.

**Comment by CWood-sdf** [comment]
> If I'm getting this right do you mean in a sense that icons can be configured like:
> ```Lua
> require("spaceport").setup({
> 	icons = {
> 		File = "",
> 		Dir = "",
> 		Remaps = "",
> 		Pinned = "",
> 		Today = "",
> 		Yesterday = "",
> 		Week = "",
> 		Month = "",
> 		Long = "",
> 	},
> })
> ```
> 
> And that the `_getIcon()` function can be used to prefix the titles?
> Or do you mean that instead of prefixing the icon value can be used to completely replace the title?
> I'm guessing you mean prefix.

Yeah, we should add prefixes for the other title options as well. Also, could we not have the keys for the icons table to be capitalized

**Comment by CWood-sdf** [comment]
I changed the icons to be non-capitalized, as that is just my personal preference. I also simplified the getIcons function to be a little easier to read

**Comment by CWood-sdf** [comment]
I also just added the ability to modify the name screen (and also moved the name_blue_green and name_blue into the name screen)

**Comment by HandyGold75** [comment]
Good remarks, I'm guessing name_blue.lua and name_blue_green.lua weren't removed due to preventing breaking changes for current configs?

Just added icons for titles, feel free to change the defaults to you're liking.

**Comment by HandyGold75** [comment]
I've noticed the project mainly uses spaces but the last changes to name.lua used tabs.
Just wanted to know which I should use in this project going forward.

**Comment by CWood-sdf** [comment]
yeah, sorry about the formatting issues. I never use tabs, so idk how they got in there. I added a .editorconfig, so you should just be able to `vim.lsp.buf.format()` and it should all work now. I would rather not remove name_blue and name_blue_green right now just in case anyone is using it. 

Also, what highlight group are you linking to for the titles? or are you just using specific colors for your title highlights? I would like some good default colors for items besides just linking everything to the `Normal` hl group. 

Anyways, unless you have some other changes you would like to suggest, I feel like this PR is ready to merge right now

**Comment by HandyGold75** [comment]
Currently, I run this config (Lazy)

```Lua
return {
	{
		-- "CWood-sdf/spaceport.nvim",
		dir = "/home/handygold75/Repos/spaceport.nvim",
		name = "spaceport",
		lazy = false,
		config = function()
			local _local_remaps = {
				lines = {},
				topBuffer = 0,
				title = nil,
				remaps = {
					{ mode = "n", key = "h", description = " Home", action = function() require("spaceport.data").cd({ dir = "~/", isDir = true }) end },
					{ mode = "n", key = "df", description = " DotFiles", action = function() require("spaceport.data").cd({ dir = "~/.dotfiles/", isDir = true }) end },
					{ mode = "n", key = "l", description = "󰒲 Lazy", action = ":Lazy<CR>" },
					{ mode = "n", key = "m", description = " Mason", action = ":Mason<CR>" },
				},
			}

			vim.api.nvim_set_hl(0, "SpaceportRemapTitle", {
				fg = "#9999FF",
			})
			vim.api.nvim_set_hl(0, "SpaceportRecentsTitle", {
				fg = "#9999FF",
			})

			require("spaceport").setup({
				projectEntry = "NvimTreeOpen",
				replaceHome = true,
				lastViewTime = "pastMonth",
				sections = {
					{ "name", config = { style = "lite", gradient = "blue" } },
					"remaps",
					"recents",
					_local_remaps,
				},
			})
		end,
		keys = {
			{ "<leader>sp", ":Spaceport<CR>", { "n" }, desc = "[s]pace[p]ort" },
		},
	},
}
```

Which results in these visuals

image


I'm not familiar with highlighting groups at all so I just bound them to specific colors that work with my color scheme, this would be a bad default IMO. Maybe if you want to include some parts as examples but that is up to you.
Feel free to merge the PR for the moment I'm through my ideas on improvements.

**Comment by CWood-sdf** [comment]
yeah that makes sense. anyway, thanks for all your help on this PR!

**Pull request merged**
